backend/requirements.txt, insert_food_data.py
Added some dependencies to requirements.txt that were missing.
Fixed insert error while inserting food data
=> Startup bugfixes

backend/base.py, frontend/src/components/Profile.js
Adding BMI calculation in profile page closing #8
=> BMI calculation

backend/base.py, frontend/package.json, frontend/src/components/authentication/SignIn.js, frontend/src/index.js
Added Sign in with google leveraging OAuth
=> Feature google sign in

frontend/src/components/authentication/SignIn.js
=> UI refactored

backend/base.py, frontend/src/components/Profile.js, frontend/src/components/UserCaloriesPage.js
Modified food selection into a searchable dropdown menu.
Added user activity level to personal goals in profile tab.
Closes #15 
Partially solves #13
=> Searchable dropdown, personal goals 

backend/base.py, frontend/src/components/Profile.js
Calculates and updates TDEE.
Closes #9  and resolves #10
=> TDEE feature

backend/base.py, frontend/src/components/Profile.js
=> Target calories and BMI instant update & bug resolution with update button

backend/base.py, frontend/src/components/Header.js, frontend/src/components/Meals.js, frontend/src/components/Router.js
Added "My meals" page to website
Allows user to create custom foods with their calorie information.
Allows user to create custom meals with multiple ingredients(foods).
Implements and closes #17, #18
=> Create Custom Foods and meals

backend/base.py, frontend/src/components/Events.js
Made entire event card clickable, 
Can enroll as well as unenroll from events in events page.
Closes #35 
Resolves #21
=> Events allow unenrollment

backend/base.py, frontend/src/components/Header.js, frontend/src/components/Meals.js, frontend/src/components/Router.js
Loads the user's previously created custom meals and displays them.
Resolves #51
=> Custom meal cards added

frontend/src/components/UserCaloriesPage.js
Week history data fixed. Dates appear in ascending order with current date as reference point in the middle.
=> linechart fixed

Developer_README.md, README.md, backend/insert_event_data.py, backend/insert_food_data.py
1. Added Developer Documentation
2. Added new installation instructions
3. Moved insert_* files to backend folder
=> Added Developer Documentation; Added new install instructions; More

frontend/src/components/ContactUs.js
=> Contact us now has a Form for easy Emails. Fixes issue #48

frontend/src/components/Profile.js
=> Adding toggle for unit change

frontend/src/components/Profile.js
=> Checking units before POST

backend/base.py, frontend/src/components/authentication/SignIn.js
=> Saves user profile information from google

frontend/src/components/Profile.js
=> Dont allow repeated unit change

frontend/src/components/UserCaloriesPage.js
=> Calorie consumption burnout

frontend/src/components/Header.js, frontend/src/components/Router.js, frontend/src/components/faq.js
=> Adding FAQ page

frontend/src/components/App.js, frontend/src/components/ContactUs.js, frontend/src/components/Events.js, frontend/src/components/Header.js, frontend/src/components/Home.js, frontend/src/components/Meals.js, frontend/src/components/Profile.js, frontend/src/components/Router.js, frontend/src/components/UserCaloriesPage.js, frontend/src/components/faq.js
Closes #74 
Make sure to run code for sanity check before approving
=> Code cleanup

backend/test_api.py, frontend/src/App.test.js, frontend/src/ContactUs.test.js, frontend/src/Events.test.js, frontend/src/Footer.test.js, frontend/src/Header.test.js, frontend/src/Home.test.js, frontend/src/Meals.test.js, frontend/src/PrivateRoute.test.js, frontend/src/Profile.test.js, frontend/src/Router.test.js, frontend/src/UserCaloriesPage.test.js, frontend/src/components/Footer.js, frontend/src/faq.test.js
- Added test cases to cover newly added routes in backend
- Built basic test framework for frontend components
- Added simple UI test cases for some components
Resolves #80 
Closes #81
=> Test cases

.github/workflows/style_checker.yml, backend/requirements.txt, frontend/src/components/Events.js, frontend/src/components/Meals.js, frontend/src/components/Profile.js, frontend/src/components/UserCaloriesPage.js, frontend/src/components/authentication/SignIn.js
=> Fix for build script workflow

Developer_README.md, README.md, frontend/src/components/Footer.js, frontend/src/components/UserCaloriesPage.js
=> Updated dev documentation and readme
